#[derive(Debug)]
pub enum Pattern {
    SquareTopLeft,
    SquareTopRight,
    SquareBottomLeft,
    SquareBottomRight,
    StripeBottom,
    StripeTop,
    StripeLeft,
    StripeRight,
    StripeCenter,
    StripeMiddle,
    StripeDownright,
    StripeDownleft,
    StripeSmall,
    Cross,
    StraightCross,
    Border,
    CurlyBorder,
    TriangleBottom,
    TriangleTop,
    TrianglesBottom,
    TrianglesTop,
    DiagonalLeft,
    DiagonalRight,
    DiagonalLeftMirror,
    DiagonalRightMirror,
    CircleMiddle,
    RhombusMiddle,
    HalfVertical,
    HalfVerticalMirror,
    HalfHorizontal,
    HalfHorizontalMirror,
    Creeper,
    Bricks,
    Gradient,
    GradientUp,
    Skull,
    Flower,
}

impl Pattern {
    pub fn to_lowercase_string(&self) -> String {
        match self {
            Pattern::SquareTopLeft => "square_top_left",
            Pattern::SquareTopRight => "square_top_right",
            Pattern::SquareBottomLeft => "square_bottom_left",
            Pattern::SquareBottomRight => "square_bottom_right",
            Pattern::StripeBottom => "stripe_bottom",
            Pattern::StripeTop => "stripe_top",
            Pattern::StripeLeft => "stripe_left",
            Pattern::StripeRight => "stripe_right",
            Pattern::StripeCenter => "stripe_center",
            Pattern::StripeMiddle => "stripe_middle",
            Pattern::StripeDownright => "stripe_downright",
            Pattern::StripeDownleft => "stripe_downleft",
            Pattern::StripeSmall => "stripe_small",
            Pattern::Cross => "cross",
            Pattern::StraightCross => "straight_cross",
            Pattern::Border => "border",
            Pattern::CurlyBorder => "curly_border",
            Pattern::TriangleBottom => "triangle_bottom",
            Pattern::TriangleTop => "triangle_top",
            Pattern::TrianglesBottom => "triangles_bottom",
            Pattern::TrianglesTop => "triangles_top",
            Pattern::DiagonalLeft => "diagonal_left",
            Pattern::DiagonalRight => "diagonal_right",
            Pattern::DiagonalLeftMirror => "diagonal_left_mirror",
            Pattern::DiagonalRightMirror => "diagonal_right_mirror",
            Pattern::CircleMiddle => "circle_middle",
            Pattern::RhombusMiddle => "rhombus_middle",
            Pattern::HalfVertical => "half_vertical",
            Pattern::HalfVerticalMirror => "half_vertical_mirror",
            Pattern::HalfHorizontal => "half_horizontal",
            Pattern::HalfHorizontalMirror => "half_horizontal_mirror",
            Pattern::Creeper => "creeper",
            Pattern::Bricks => "bricks",
            Pattern::Gradient => "gradient",
            Pattern::GradientUp => "gradient_up",
            Pattern::Skull => "skull",
            Pattern::Flower => "flower",
        }
        .to_string()
    }
}